#This is the API in keycloak that is used to verify the access token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/OAuth2-demo-realm/protocol/openid-connect/certs
